### PR TITLE
refactor: refactor to use klog from glog

### PR DESCRIPTION
**Pull request by ashishranjan738**
Signed-off-by: Ashish Ranjan <ashishranjan738@gmail.com>

This commit refactors the code to use klog instead og glog as kubernetes from 1.13 uses klog as their default logger

**What type of PR is this?**
 /kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes # https://github.com/csi-driver/azuredisk-csi-driver/issues/41

**Special notes for your reviewer**:

**Release note**:
```

```

### CODE REVIEW

**Comment by ashishranjan738** [comment]
> @ashishranjan738 You have removed `Gopkg.lock`, that file is needed.

It is not removed it got modified as I ran the `dep ensure` to sync the packages.

**Comment by ashishranjan738** [comment]
> Also, you haven't added a vendor for `klog`. Please add that.

we don't need to add it as it is already there in our vendor.

**Comment by andyzhangx** [comment]
@ashishranjan738 pls rebase and fix the conflict, thanks.

**Comment by ashishranjan738** [comment]
@andyzhangx done.

**Pull request merged**
