### PR TITLE
fix deploy yaml files

### PR DESCRIPTION
**Pull request by lizebang**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:

```

```

### CODE REVIEW

**Comment by andyzhangx** [comment]
@lizebang how do you format this? by visual studio code?

**Comment by lizebang** [comment]
@andyzhangx Yes, by visual studio code. (Plugins: [Red Hat YAML](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) and [Microsoft Kubernetes](https://marketplace.visualstudio.com/items?itemName=ms-kubernetes-tools.vscode-kubernetes-tools))

**Comment by andyzhangx** [comment]
@lizebang make same fix on azure file driver?

**Comment by lizebang** [comment]
@andyzhangx  Yes, with pleasure.


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Pull request merged**
